// ============================================================
// PURPOSE SPHERE COMMAND CENTER — DATA MODULE
// Generated by the Claude data engine. Every number below was
// probed live from a connected tool. No mock data.
// Regenerate with the `dashboard-refresh` skill.
// ============================================================
window.DASHBOARD_DATA = {
  generatedAt: "2026-07-23T01:37:06Z",
  generatedBy: "claude-data-engine",

  // ---- source health: probed at generation time ----
  sources: {
    gmail:   { label: "GMAIL",        status: "online", probedAt: "2026-07-23T01:35:00Z", account: "purposequestinc@gmail.com" },
    gdrive:  { label: "GOOGLE DRIVE", status: "online", probedAt: "2026-07-23T01:35:00Z", account: "palmerga15@gmail.com" },
    dropbox: { label: "DROPBOX",      status: "online", probedAt: "2026-07-23T01:35:00Z", account: "Dr. G. Alfred Palmer" },
    lovable: { label: "LOVABLE",      status: "online", probedAt: "2026-07-23T01:35:00Z", account: "Gregory's Lovable" },
    github:  { label: "GITHUB",       status: "online", probedAt: "2026-07-23T01:35:00Z", account: "palmerga15-alt" }
  },

  // ---- AI MORNING BRIEFING (cross-referenced across tools) ----
  briefing: {
    date: "Wednesday, July 23, 2026",
    headline: "Webinar follow-up window is closing; a finished corporate-outreach draft is idle in Gmail; two Kenya outreach emails bounced.",
    summary: "The July 15 'Purposeology & AI' webinar was 8 days ago and the repo's offer suite for it is built but nothing in Gmail shows a post-webinar follow-up sequence going out. Meanwhile the highest-leverage assets sitting idle are a fully-written Fortune 500 outreach email (drafted June 12, never sent) and 7 Lovable sites of which only 1 is published.",
    actions: [
      {
        priority: 1,
        title: "Send the post-webinar follow-up sequence",
        detail: "The 'Purposeology & AI' webinar (July 15) is 8 days past. The offer suite exists in the repo (offers/2026-07-15-purposeology-ai-webinar-offer-suite.md) but Gmail sent-mail shows no follow-up emails since. No-show + replay emails convert as well as the live event — this window closes fast.",
        sources: ["github", "gmail"]
      },
      {
        priority: 2,
        title: "Finish and send the Fortune 500 outreach draft (idle 41 days)",
        detail: "A complete 'Transforming Business Through Purpose, Leadership, and AI' email has been sitting in Gmail drafts since June 12 with placeholder [Phone Number]/[Email]/[Website] fields. It maps directly to Strategic Priority #4 and the repo's corporate-training offer spec (offers/2026-07-14-fortune-500-corporate-training-offer.md). Fill 3 placeholders and ship it.",
        sources: ["gmail", "github"]
      },
      {
        priority: 3,
        title: "Repair the bounced Kenya outreach and resend",
        detail: "The June 29 Kenya institutional outreach (8 recipients incl. Strathmore, Daystar, Kenyatta University) triggered 2 mailer-daemon bounces. Those institutions never got the pitch. Verify the bad addresses and resend — this was the global-speaking priority in motion.",
        sources: ["gmail"]
      },
      {
        priority: 4,
        title: "Verify Constant Contact to unblock email marketing",
        detail: "Constant Contact (trial started July 17) is still waiting on email verification — every planned sequence (webinar reminders, follow-ups, nurture) is blocked until this ~2-minute step is done.",
        sources: ["gmail"]
      },
      {
        priority: 5,
        title: "Publish Alliance Glow (or decide not to)",
        detail: "7 Lovable projects exist; only 1 is published (grow-your-web-garden-purposeology-15.lovable.app). Alliance Glow — the Purpose Power Alliance landing page — was finished July 20 and is sitting unpublished. An unpublished landing page captures zero signups.",
        sources: ["lovable"]
      },
      {
        priority: 6,
        title: "Reply check: John Stanko thread",
        detail: "Active mentor/peer correspondence with John Stanko (last exchange July 1–2). Three weeks of silence on a warm relationship thread — worth a touch-base.",
        sources: ["gmail"]
      }
    ]
  },

  // ---- REVENUE PIPELINE (from repo offer specs; money values flagged) ----
  pipeline: {
    streams: [
      { name: "Webinar Offer Suite", stage: "LAUNCHED JUL 15 — FOLLOW-UP DUE", doc: "offers/2026-07-15-purposeology-ai-webinar-offer-suite.md", money: null },
      { name: "Purposeologist Certification", stage: "OFFER SPEC COMPLETE", doc: "offers/2026-07-14-online-purposeologist-certification-school.md", money: "$3,495 core credential" },
      { name: "Corporate Delivery License", stage: "OFFER SPEC COMPLETE", doc: "offers/2026-07-14-online-purposeologist-certification-school.md", money: "$12,000–$25,000+/yr" },
      { name: "Fortune 500 Training", stage: "SPEC DONE — OUTREACH DRAFT IDLE", doc: "offers/2026-07-14-fortune-500-corporate-training-offer.md", money: null },
      { name: "Global Speaking", stage: "OUTREACH ACTIVE (KENYA/GHANA)", doc: "offers/2026-07-14-global-speaking-keynote-offer.md", money: null },
      { name: "purposeology.ai Platform", stage: "RESEARCH + SPEC COMPLETE", doc: "offers/2026-07-14-purposeology-ai-platform-offer.md", money: null }
    ],
    priorities: [
      { rank: 1, name: "Books, seminars, workshops", note: "most immediate revenue path" },
      { rank: 2, name: "Certification school", note: "scalable licensing model" },
      { rank: 3, name: "Global speaking", note: "Kenya/Ghana outreach in motion" },
      { rank: 4, name: "Fortune 500 training", note: "outreach draft ready, unsent" },
      { rank: 5, name: "purposeology.ai", note: "long-term, highest impact" }
    ]
  },

  // ---- GMAIL ----
  gmail: {
    unreadEstimate: 201,
    draftCount: 3,
    keyDrafts: [
      { subject: "Transforming Business Through Purpose, Leadership, and AI", note: "Fortune 500 outreach — complete, placeholders unfilled", idleSince: "2026-06-12" },
      { subject: "(no subject) → marketing@esvachamber.org", note: "empty draft to ES VA Chamber", idleSince: "2026-06-12" }
    ],
    alerts: [
      { type: "BOUNCE", text: "2 mailer-daemon bounces on June 29 Kenya outreach (8 recipients)" },
      { type: "BLOCKED", text: "Constant Contact email verification pending since Jul 17" },
      { type: "ACTION", text: "Acquisition.com offers-workshop 'last call' received Jul 22" }
    ],
    recentSent: [
      { to: "info@marylandbcc.org", date: "2026-07-05", note: "Maryland Black Chamber outreach" },
      { to: "johnstanko@gmail.com", date: "2026-07-02", note: "mentor/peer thread (4 msgs)" },
      { to: "8 Kenya institutions", date: "2026-06-29", note: "education/enterprise outreach — 2 bounced" },
      { to: "3 Kenya SME agencies", date: "2026-06-29", note: "MSEA, Nyota Project, Kenya Chamber" },
      { to: "info@gea.gov.gh", date: "2026-06-29", note: "Ghana Enterprises Agency" }
    ],
    recentUnread: [
      { from: "LinkedIn", subject: "Add Warner H. Session (Session Law Firm)", date: "2026-07-22" },
      { from: "OpusClip", subject: "Top features to help you save time", date: "2026-07-22" },
      { from: "Base44", subject: "Welcome offer: 30% off — expires soon", date: "2026-07-22" },
      { from: "Acquisition.com", subject: "last call — offers workshop", date: "2026-07-22" },
      { from: "Acquisition.com", subject: "Mozi Minute: My Highest ROI Decisions", date: "2026-07-21" },
      { from: "Kajabi", subject: "Watch me build a whole business in one hour", date: "2026-07-21" }
    ]
  },

  // ---- GOOGLE DRIVE ----
  gdrive: {
    recentFiles: [
      { title: "IMG_-oow2gt.jpg", type: "image", modified: "2026-07-22", note: "" },
      { title: "IMG_20221226_181648_326.jpg", type: "image", modified: "2026-07-22", note: "book/brand collage w/ Myles Munroe" },
      { title: "FB_IMG_1685161138420.jpg", type: "image", modified: "2026-07-22", note: "Purpose-ology book series art" },
      { title: "Howard University Hospital BILL Palmer, G.pdf", type: "pdf", modified: "2026-07-22", note: "patient balance", money: "$17,735.40" },
      { title: "DrG_Alfred_Palmer_Full_Bio.md", type: "doc", modified: "2026-07-13", note: "speaker bio — pipeline input" },
      { title: "Quick Avatar Video.mp4", type: "video", modified: "2026-07-21", note: "HeyGen avatar asset (47 MB)" },
      { title: "final PALMERGA promo-1", type: "video", modified: "2026-07-16", note: "promo video (304 MB)" },
      { title: "VideoPrayer.m4a + Purpose Prayer 002", type: "audio", modified: "2026-07-19", note: "prayer audio series (x3)" }
    ]
  },

  // ---- DROPBOX ----
  dropbox: {
    account: "Dr. G. Alfred Palmer",
    itemCount: 4,
    fileRequests: 0,
    note: "Effectively dormant — newest business file is from 2020.",
    entries: [
      { name: "Paper Docs/", modified: "2025-11-18", type: "folder" },
      { name: "BUILT TO SERVE WORKBOOK.pdf", modified: "2020-03-12", type: "pdf" },
      { name: "Get Started with Dropbox.pdf", modified: "2019-10-29", type: "pdf" }
    ]
  },

  // ---- LOVABLE ----
  lovable: {
    workspace: "Gregory's Lovable",
    projectCount: 7,
    publishedCount: 1,
    projects: [
      { name: "Alliance Glow", status: "UNPUBLISHED", edited: "2026-07-20", note: "Purpose Power Alliance landing — finished, not live" },
      { name: "Galfred Palmer Landing", status: "UNPUBLISHED", edited: "2026-07-15", note: "bio + speaking requests" },
      { name: "Your Dream Website", status: "PUBLISHED", edited: "2026-06-28", url: "grow-your-web-garden-purposeology-15.lovable.app" },
      { name: "Connect Analytics To You", status: "UNPUBLISHED", edited: "2026-06-28", note: "GA integration" },
      { name: "My Story Hub", status: "UNPUBLISHED", edited: "2026-06-24", note: "blog" },
      { name: "Survey Responses Inbox", status: "UNPUBLISHED", edited: "2026-06-12", note: "survey viewer" },
      { name: "Purpose Fuel", status: "UNPUBLISHED", edited: "2026-06-06", note: "purpose discovery app" }
    ]
  },

  // ---- GITHUB (this repo) ----
  github: {
    repo: "palmerga15-alt/purpose-sphere-revenue-system",
    openIssues: 0,
    openPRs: 0,
    workflowRuns: 0,
    assetCounts: { research: 4, offers: 5, contentAngles: 5 },
    recentCommits: [
      { msg: "Add content angles for purposeology.ai priority (#5)", date: "2026-07-14" },
      { msg: "Add offer spec for purposeology.ai priority (#5)", date: "2026-07-14" },
      { msg: "Add market research for purposeology.ai priority (#5)", date: "2026-07-14" },
      { msg: "Add content angles for Fortune 500 corporate training (#4)", date: "2026-07-14" },
      { msg: "Add offer spec for Fortune 500 corporate training (#4)", date: "2026-07-14" },
      { msg: "Refine certification school pricing vs market research", date: "2026-07-14" }
    ]
  }
};
